//Adicionar strings em ordem alfabetica, por favor!

const globalStrings = {
  CLIENT_TITLE: "Negócio Direto",
  CONTINUE: "Para continuar, precisamos\nque informe suas credenciais",
  COST: "Custo",
  CPF: "CPF",
  CREATE_ACCOUNT: "Crie sua conta",
  EMAIL: "E-mail",
  EXIT: "Sair",
  FINISH_SIGN_UP: "Finalizar Cadastro",
  FULL_NAME: "Nome completo",
  GO_AHEAD: "Prosseguir",
  ID: "ID",
  INSERT_EMAIL: 'Insira seu e-mail',
  INSERT_PASSWORD: 'Insira sua senha',
  INVALID_CPF: "Não é um CPF válido",
  INVALID_EMAIL: "Não é um endereço válido",
  INVALID_FULL_NAME: "Esse não é seu nome completo",
  INVALID_PASSWORD: "A senha deve possuir 8 ou mais dígitos",
  INVALID_PHONE: "Não é um número válido",
  PLACEHOLDER_CPF: "123.456.789-12",
  PLACEHOLDER_EMAIL: "usuario@email.com",
  PLACEHOLDER_FULL_NAME: "Seu Nome Completo",
  PLACEHOLDER_PASSWORD: "@SenhaCom8+Digitos@",
  PLACEHOLDER_PASSWORD_CONFIRMATION: "Confirme sua senha",
  PLACEHOLDER_PHONE: "(21) 54321-4321",
  PASSWORD: "Senha",
  PHONE_NUMBER: "Telefone",
  QUANTITY: "Quantidade",
  SIGN_UP: "Cadastro",
  USER_NOT_FOUND: "Usuário ou senha incorretos",
  WELCOME: "Bem-vindo ao\nNegócio Direto", 
};

export default globalStrings